CREATE TABLE public.purchases_positions
(
    purchase_number bigint NOT NULL,
    amount double precision,
    reclamation_exist character(1) COLLATE pg_catalog."default",
    product_id bigint,
    purchase_id bigint NOT NULL,
    CONSTRAINT purchases_positions_pkey PRIMARY KEY (purchase_number),
    CONSTRAINT fk3waij916fb78mx0agdlesf68o FOREIGN KEY (product_id)
        REFERENCES public.products (product_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkikfvq9oiayewb5q3v3sh5k93s FOREIGN KEY (purchase_id)
        REFERENCES public.purchases (purchase_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.purchases_positions
    OWNER to postgres;

    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (1,1,25,0.5,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (1,2,20,1,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (1,3,5,10,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (1,4,8,8,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (1,5,7,5,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (2,1,9,2,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (3,1,1,1,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (3,2,17,7,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (3,3,22,12,'N');
    Insert into PURCHASES_POSITIONS (PURCHASE_ID,PURCHASE_NUMBER,PRODUCT_ID,AMOUNT,RECLAMATION_EXIST) values (3,4,7,6,'N');
