CREATE TABLE public.supplier
(
    supplier_id bigint NOT NULL,
    activity_status character varying(255) COLLATE pg_catalog."default",
    supplier_name character varying(255) COLLATE pg_catalog."default",
    mode_of_transport_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT supplier_pkey PRIMARY KEY (supplier_id),
    CONSTRAINT fklx99i3ebmuq0647js1v4qrgpd FOREIGN KEY (mode_of_transport_code)
        REFERENCES public.types_of_transport (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.supplier
    OWNER to postgres;

    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (1,'Morliny','VAN','A');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (2,'Koral','BUS','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (3,'Pepco','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (4,'Lidl','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (5,'Obi','VAN','A');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (6,'Decathlon','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (7,'Biedronka','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (8,'Auchan','BUS','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (9,'Lewiatan','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (10,'Intermarche','VAN','A');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (11,'Bricomarche','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (12,'Tesco','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (13,'E.Leclerc','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (14,'Amica','BUS','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (15,'Avon','AUT','A');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (16,'Puma','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (17,'Lego','VAN','A');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (18,'Militaria','TIR','N');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (19,'Delikatesy','AUT','A');
    Insert into SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,MODE_OF_TRANSPORT_CODE,ACTIVITY_STATUS) values (20,'Jogobella','VAN','A');
